#!/bin/bash
#=================================================================================
# Install Eclipse JEE Mars on Ubuntu 16.04 Desktop
#
# Version: 1.0.0
# Date: 07 Jun 2016
# Author: Dave Nicolette
#=================================================================================

echo ' '
echo 'Installing Eclipse JEE Mars'

mkdir -p "$HOME/tmp" && pushd "$HOME/tmp" >/dev/null || exit
wget http://mirror.csclub.uwaterloo.ca/eclipse/technology/epp/downloads/release/mars/2/eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz
pushd /opt
sudo cp "$HOME/tmp/eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz" .
sudo tar -zxvf eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz
sudo rm eclipse-jee-mars-2-linux-gtk-x86_64.tar.gz
popd

echo ' '
echo 'Workaround for bug in Eclipse - force it to use GTK 2 instead of 3'

sudo sed -i '/--launcher.appendVmargs/ i \--launcher.GTK_version\n2' /opt/eclipse/eclipse.ini

pushd "$HOME"
echo ' ' >> ~/.profile
echo '# add eclipse to PATH' >> ~/.profile
echo 'PATH=$PATH:/opt/eclipse' >> ~/.profile
. .profile
popd

pushd /usr/share/applications
sudo cp "$INSTALL_DIR/$COMMON_DIR/eclipse.desktop" .
popd
